---
kind: pipeline
name: x86_64

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: compose:1.24.1
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - ./utils/generate-crypto-stuff.sh
  - up -f /drone/src/docker-compose.yaml

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
