sudo: 'required'
language: bash
dist: bionic

services:
  - docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - ./.travis/main.sh

script:
  - set -e # https://github.com/travis-ci/travis-ci/issues/1066
  - ./utils/generate-crypto-stuff.sh
  - cp config/strongHome-config-test.yaml config/strongHome-config.yaml
  - docker-compose --compatibility -f docker-compose.yml -f config/docker-compose.test.yml up --build
  - exit $(docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v '^0' | wc -l | tr -d ' ')

notifications:
  email: false
