sudo: 'required'
language: bash
dist: bionic

services:
  - docker

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

matrix:
  include:
  - name: "x86_64"
    env: BUILDPLATFORM=linux/amd64
  - name: "arm32v7"
    env: BUILDPLATFORM=linux/arm/v7
  - name: "arm64"
    env: BUILDPLATFORM=linux/arm64

before_install:
  - ./.travis/main.sh
  - find services/ -type f -name Dockerfile -exec sed -i 's/FROM /ARG BUILDPLATFORM\nFROM --platform=$BUILDPLATFORM /g' {} \;

script:
  - set -e # https://github.com/travis-ci/travis-ci/issues/1066
  - ./utils/generate-crypto-stuff.sh
  - cp config/strongHome-config-test.yaml config/strongHome-config.yaml
  - docker-compose build --build-arg BUILDPLATFORM=$BUILDPLATFORM
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up
  - docker-compose ps
  - exit $(docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v '^0' | wc -l | tr -d ' ')

# after_failure:
#   - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build #Try without memmory limits
#   - docker-compose ps

notifications:
  email: false
