language: bash

services:
  - docker

before_install:
  - ./utils/generate-crypto-stuff.sh

script:
  - set -e
  - docker-compose --compatibility -f docker-compose.yml -f test/docker-compose.test.yml up --build
  - exit $(docker-compose ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v '^0' | wc -l | tr -d ' ')
