version: '3'
services:
  openldap:
    build: ldap
    container_name: openldap
    command: --loglevel debug
    environment:
      LDAP_ORGANISATION: "strongHome"
      LDAP_DOMAIN: "${LOCAL_DOMAIN}"
      LDAP_ADMIN_PASSWORD: "admin"
      HOSTNAME: ldap.${LOCAL_DOMAIN}
    volumes:
      - $PWD/config/strongHome-schema.yaml:/strongHome/strongHome-schema.yaml
      - $PWD/config/strongHome-config-example.yaml:/strongHome/strongHome-config.yaml
      # - $PWD/ldap/ldap:/var/lib/ldap
      # - $PWD/ldap/slapd:/etc/ldap/slapd.d
      # - $PWD/openssl-ca:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
    domainname: "${LOCAL_DOMAIN}" # important: same as hostname
    hostname: "ldap"
    networks:
      - ldap-net

  webldap:
    image: osixia/phpldapadmin:0.8.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - "443:443"
      - "80:80"
    networks:
      - ldap-net

networks:
  ldap-net:
