version: '3.3'
services:
  openldap:
    build: ldap
    command: --loglevel info
    hostname: openldap
    # domainname: openldap
    environment:
      LDAP_ORGANISATION: "strongHome"
      LDAP_DOMAIN: "${LOCAL_DOMAIN}"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS_CRT_FILENAME: ldap.${LOCAL_DOMAIN}.pem
      LDAP_TLS_KEY_FILENAME: ldap.${LOCAL_DOMAIN}-key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - type: bind
        source: $PWD/config/strongHome-schema.yaml
        target: /strongHome/strongHome-schema.yaml
      - type: bind
        source: $PWD/config/strongHome-config-example.yaml
        target: /strongHome/strongHome-config.yaml
      - type: bind
        source: $PWD/openssl-ca/ldap.${LOCAL_DOMAIN}-key.pem
        target: /container/service/slapd/assets/certs/ldap.${LOCAL_DOMAIN}-key.pem
      - type: bind
        source: $PWD/openssl-ca/ldap.${LOCAL_DOMAIN}.pem
        target: /container/service/slapd/assets/certs/ldap.${LOCAL_DOMAIN}.pem
      - type: bind
        source: $PWD/openssl-ca/ca.pem
        target: /container/service/slapd/assets/certs/ca.pem
    networks:
      - ldap-net
      - radius-net
    env_file:
      - .env

  freeradius:
    build: radius
    # command: -X
    environment:
      LOCAL_DOMAIN: "${LOCAL_DOMAIN}"
    volumes:
      - type: bind
        source: $PWD/openssl-ca/dh
        target: /cert/dh
      - type: bind
        source: $PWD/openssl-ca/ca.pem
        target: /cert/ca.pem
      - type: bind
        source: $PWD/openssl-ca/radius.${LOCAL_DOMAIN}.pem
        target: /cert/radius.${LOCAL_DOMAIN}.pem
      - type: bind
        source: $PWD/openssl-ca/radius.${LOCAL_DOMAIN}-key.pem
        target: /cert/radius.${LOCAL_DOMAIN}-key.pem
      - type: bind
        source: $PWD/openssl-ca/radius-shared-secret
        target: /cert/radius-shared-secret
    depends_on:
      - openldap
    ports:
      - "1812-1813:1812-1813/udp"
    networks:
      - radius-net
    env_file:
      - .env

  # webldap:
  #   image: osixia/phpldapadmin:0.8.0
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: openldap
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - ldap-net

networks:
  ldap-net:
  radius-net:
