version: '3.3'
services:
  openldap:
    build: services/ldap
    command: --loglevel info
    hostname: openldap
    environment:
      LDAP_ORGANISATION: "strongHome"
      LDAP_DOMAIN: "strongHome.vk496"
      LDAP_TLS_CRT_FILENAME: ldap.pem
      LDAP_TLS_KEY_FILENAME: ldap-key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - type: bind
        source: $PWD/config/strongHome-schema.yaml
        target: /strongHome/strongHome-schema.yaml
      - $PWD/config/strongHome-config.yaml:/strongHome/strongHome-config.yaml
      - type: bind
        source: $PWD/openssl-ca/ldap-key.pem
        target: /container/service/slapd/assets/certs/ldap-key.pem
      - type: bind
        source: $PWD/openssl-ca/ldap.pem
        target: /container/service/slapd/assets/certs/ldap.pem
      - type: bind
        source: $PWD/openssl-ca/ca.pem
        target: /container/service/slapd/assets/certs/ca.pem
      - type: bind
        source: $PWD/openssl-ca/admin-ro-pw
        target: /cert/admin-ro-pw
    networks:
      - ldap-net
      - radius-net
      - redis-net

  freeradius:
    build: services/radius
    # command: -X
    volumes:
      - type: bind
        source: $PWD/openssl-ca/dh
        target: /cert/dh
      - type: bind
        source: $PWD/openssl-ca/ca.pem
        target: /cert/ca.pem
      - type: bind
        source: $PWD/openssl-ca/radius.pem
        target: /cert/radius.pem
      - type: bind
        source: $PWD/openssl-ca/radius-key.pem
        target: /cert/radius-key.pem
      - type: bind
        source: $PWD/openssl-ca/radius-shared-secret
        target: /cert/radius-shared-secret
      - type: bind
        source: $PWD/openssl-ca/admin-ro-pw
        target: /cert/admin-ro-pw
    depends_on:
      - openldap
    ports:
      - "1812-1813:1812-1813/udp"
    networks:
      - radius-net
      - redis-net

  redis:
    image: redis:alpine
    hostname: redis
    networks:
      - redis-net


  # webldap:
  #   image: osixia/phpldapadmin:0.8.0
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: openldap
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - ldap-net

networks:
  ldap-net:
  radius-net:
  redis-net:
