version: '3'
services:
  openldap:
    build: ldap
    command: --loglevel info
    environment:
      LDAP_ORGANISATION: "strongHome"
      LDAP_DOMAIN: "${LOCAL_DOMAIN}"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS_CRT_FILENAME: ldap.${LOCAL_DOMAIN}.pem
      LDAP_TLS_KEY_FILENAME: ldap.${LOCAL_DOMAIN}-key.pem
      LDAP_TLS_CA_CRT_FILENAME: ca.pem
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_VERIFY_CLIENT: try
    volumes:
      - $PWD/config/strongHome-schema.yaml:/strongHome/strongHome-schema.yaml
      - $PWD/config/strongHome-config-example.yaml:/strongHome/strongHome-config.yaml
      - $PWD/openssl-ca/ldap.${LOCAL_DOMAIN}-key.pem:/container/service/slapd/assets/certs/ldap.${LOCAL_DOMAIN}-key.pem
      - $PWD/openssl-ca/ldap.${LOCAL_DOMAIN}.pem:/container/service/slapd/assets/certs/ldap.${LOCAL_DOMAIN}.pem
      - $PWD/openssl-ca/ca.pem:/container/service/slapd/assets/certs/ca.pem
    networks:
      - ldap-net
      - radius-net

  freeradius:
    build: radius
    # command: -X
    environment:
      LOCAL_DOMAIN: "${LOCAL_DOMAIN}"
    volumes:
      - $PWD/openssl-ca/radius.${LOCAL_DOMAIN}-key.pem:/cert/radius.${LOCAL_DOMAIN}-key.pem
      - $PWD/openssl-ca/radius.${LOCAL_DOMAIN}.pem:/cert/radius.${LOCAL_DOMAIN}.pem
      - $PWD/openssl-ca/ca.pem:/cert/ca.pem
      - $PWD/openssl-ca/dh:/cert/dh
    depends_on:
      - openldap
    ports:
      - "1812-1813:1812-1813/udp"
    networks:
      - radius-net

  # webldap:
  #   image: osixia/phpldapadmin:0.8.0
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: openldap
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     - ldap-net

networks:
  ldap-net:
  radius-net:
