strongHome:
  list_services:
    - 802.11x
    - OwnCloud
    - Email
    - VoIP
  list_users:
    - user: admin
      admin: yes
      password: Asdfaksdnjasdnjasnjdas
      services:
        - 802.11x
        - OwnCloud
        - Email
        - VoIP
    - user: test1
      password: skdjaskjdasjk
      services:
        - 802.11x
