type: map
required: yes
mapping:
 "strongHome":
    type: map
    required:  yes
    mapping:
      "admin_password":
        type: str
        required: yes
        desc: LDAP Administrator password
        pattern: ^{CRYPT}\$.+
      "list_services":
        type: seq
        required: true
        desc: List of services
        sequence:
          - type: str
            enum: &list-services
              - Radius
              - OwnCloud
              - Email
              - VoIP
      "list_users":
        type: seq
        required: true
        desc: List of the users to deploy to the LDAP
        sequence:
          - type: map
            mapping:
              "user":
                type: str
                desc: The username of the user
                required: yes
                unique: true
              "password":
                type: str
                desc: Password of the user
                required: yes
              "services":
                type: seq
                desc: List of services that a user would have access
                required: yes
                sequence:
                  - type: str
                    enum: *list-services
